model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: target
    cond_stage_key: original
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 192
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_heads: 1
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 768
    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
      params:
        placeholder: 10
    cond_stage_config:
      target: ldm.modules.srt_modules.encoder.ImprovedSRTEncoder
data:
  target: main.DataModuleFromConfig
  params:
    num_workers: 0
    batch_size: 12
    wrap: True
    train:
      target: ldm.data.nmr_sharded.NMRShardedDataset
      params:
        path: /scratch/work/spieglb1/datasets/NMR_sharded
        mode: train

    test:
      target: ldm.data.nmr_sharded.NMRShardedDataset
      params:
        path: /scratch/work/spieglb1/datasets/NMR_sharded
        mode: test

    validation:
      target: ldm.data.nmr_sharded.NMRShardedDataset
      params:
        path: /scratch/work/spieglb1/datasets/NMR_sharded
        mode: val


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True